# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='here', max_length=40, verbose_name='Nombre del equipo'),
            preserve_default=False,
        ),
    ]
