# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 3, 15, 19, 15, 32, 669403, tzinfo=utc), max_length=40, verbose_name='Nombre del equipo'),
            preserve_default=False,
        ),
    ]
