# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nombre del equipo')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to=b'', verbose_name='Imagenes')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=400, verbose_name='Descripci\xf3n del equipo'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to=b'', verbose_name='Fotograf\xeda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Team'),
        ),
    ]
