# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=400, verbose_name='Descripci\xf3n del equipo'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='name', max_length=40, verbose_name='Nombre del equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, upload_to=b'', verbose_name='Fotograf\xeda'),
        ),
    ]
