# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electr\xf3nico')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellidos')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(10, 'Cedula de ciudadan\xeda'), (20, 'Cedula de extranjer\xeda'), (30, 'Pasaporte')], verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=64, verbose_name='N\xfamero de documento')),
                ('document_expedition', models.CharField(blank=True, max_length=128, null=True, verbose_name='Lugar de expedici\xf3n')),
                ('nationality', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nacionalidad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('department', models.CharField(blank=True, max_length=128, null=True, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Direcci\xf3n')),
                ('mobile_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tel\xe9fono Celular')),
                ('home_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tel\xe9fono Fijo')),
                ('genre', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Masculino'), (20, 'Femenino'), (30, 'Otro')], null=True, verbose_name='Genero')),
                ('company_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Empresa')),
                ('company_department', models.CharField(blank=True, max_length=128, null=True, verbose_name='Departamento')),
                ('company_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ciudad')),
                ('company_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Direcci\xf3n')),
                ('company_position', models.CharField(blank=True, max_length=128, null=True, verbose_name='Cargo')),
                ('work_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tel\xe9fono')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si puede entrar al sitio de administraci\xf3n.', verbose_name='Administrador')),
                ('is_active', models.BooleanField(default=False, help_text='Indica si el usuario puede ser tratado como activo.', verbose_name='Activo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('document_type', 'document_number')]),
        ),
    ]
