# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='user', max_length=100, unique=True, verbose_name='Password de usuario'),
            preserve_default=False,
        ),
    ]
