# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20160423_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electr\xf3nico')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellidos')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(10, 'Cedula de ciudadan\xeda'), (20, 'Cedula de extranjer\xeda'), (30, 'Pasaporte')], verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=64, verbose_name='N\xfamero de documento')),
                ('document_expedition', models.CharField(blank=True, max_length=128, null=True, verbose_name='Lugar de expedici\xf3n')),
                ('nationality', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nacionalidad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('department', models.CharField(blank=True, max_length=128, null=True, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Direcci\xf3n')),
                ('mobile_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tel\xe9fono Celular')),
                ('genre', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Masculino'), (20, 'Femenino'), (30, 'Otro')], null=True, verbose_name='Genero')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userdata',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='userdatacomplete',
            unique_together=set([('document_type', 'document_number')]),
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='company_city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='company_department',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='company_position',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='document_expedition',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='work_phone',
        ),
    ]
