# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20160424_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDataComplete',
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 25, 19, 49, 42, 131357, tzinfo=utc), verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='department',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='document_expedition',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Lugar de expedici\xf3n'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='document_number',
            field=models.CharField(default=1212, max_length=64, verbose_name='N\xfamero de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Cedula de ciudadan\xeda'), (20, 'Cedula de extranjer\xeda'), (30, 'Pasaporte')], default=10, verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='hola@hola.com', max_length=254, unique=True, verbose_name='Correo electr\xf3nico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Masculino'), (20, 'Femenino'), (30, 'Otro')], null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tel\xe9fono Celular'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='nationality',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterUniqueTogether(
            name='userdata',
            unique_together=set([('document_type', 'document_number')]),
        ),
    ]
